[workspace]
name = "hello-pkg"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[dependencies]
make = "*"
gcc = "*"
python = ">=3.14.3,<3.15"
numpy = ">=2.4.2,<3"
packaging = ">=26.0,<27"

[tasks]
install-dev = { cmd = "pip install -e . --break-system-packages", depends-on = ["build"] }
hello-c = { cmd = "./src/hello", depends-on = ["build"] }
hello-py = { cmd = "python hello-pkg/hello.py", depends-on = ["build"] }

# Manual build/clean tasks
build = { cmd = "make -C src" }
clean = { cmd = "make -C src clean && openmdao clean -f" }

